config/routes.rb
Rails.application.routes.draw do
  resources :potions
  root 'potions#index'

end

app/models/potion.rb
class Potion < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "400x400#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/potions_controller.rb
class PotionsController < ApplicationController
  before_action :find_potion, only: [:show, :edit, :update, :destroy]

  def index
    @potion = Potion.all.order("created_at DESC")
  end

  def new
    @potion = Potion.new
  end

  def show
  end

  def create
    @potion = Potion.new(potion_params)
    if @potion.save
      redirect_to @potion, notice: "Successfully created a new potion."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @potion.update(potion_params)
      redirect_to @potion, notice: "Successfully updated your new potion."
    else
      render 'edit'
    end
  end

  def destroy
    @potion.destroy
    redirect_to root_path, notice: "Successfully deleted your potion."
  end

  private

    def potion_params
      params.require(:potion).permit(:title, :description, :image)
    end

    def find_potion
      @potion = Potion.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/potions_helper.rb
module PotionsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Share your potions!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  = render 'partials/navbar'

  = render 'partials/flash'

  .container
    = yield

app/views/partials/_flash.html.haml
.container
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "alert"

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand= link_to "Cauldron", root_path

    %ul.nav.navbar-nav.navbar-right
      %li= link_to "Potion", new_potion_path
      %li= link_to "Sign Out", root_path

app/views/potions/_form.html.haml
= simple_form_for @potion, html: { multipart: true } do |f|
  - if @potion.errors.any?
    #errors
      %p
        = @potion.errors.count
        Prevented this potion from saving
      %ul
        - @potion.errors.full_messages.each do |msg|
          %li= msg
  .pane-body
    = f.input :title, input_html: { class: "form-control" }
    = f.input :description, input_html: { class: "form-control" }
    = f.input :image, input_html: { class: "form-control" }

    = f.button :submit, class: "btn btn-primary"

app/views/potions/edit.html.haml
%h1 Edit Potion

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/potions/index.html.haml
- @potion.each_slice(3) do |potions|
  .row
    - potions.each do |potion|
      .col-md-4
        .potion
          .image_wrapper
            = link_to potion do
              = image_tag potion.image.url(:medium)
          %h2= link_to potion.title, potion

app/views/potions/new.html.haml
%h1 New Potion

= render 'form'

%br/

= link_to "Back", root_path

app/views/potions/show.html.haml
= image_tag @potion.image.url(:medium, class: "potion_image")
%h1= @potion.title
%p= @potion.description

= link_to "Back", root_path, class: "btn btn-default"
= link_to "Edit", edit_potion_path, class: "btn btn-default"
= link_to "Delete", potion_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"